
# Field-level logical equivalence mappings
# Maps legacy Struts elements to modern Angular elements by their functional purpose

field_mappings:
  # Form field mappings
  forms:
    # Login form
    login:
      legacy:
        username_field: "input[name='username'], input[id*='username'], input[placeholder*='username'], input[placeholder*='user']"
        password_field: "input[name='password'], input[id*='password'], input[type='password']"
        submit_button: "input[type='submit'], button[type='submit'], input[value*='login'], button:contains('Login')"
      modern:
        username_field: "input[formControlName='username'], input[data-testid='username'], input[placeholder*='email'], input[placeholder*='username']"
        password_field: "input[formControlName='password'], input[data-testid='password'], input[type='password']"
        submit_button: "button[type='submit'], button:contains('Sign In'), button:contains('Login')"
    
    # Registration form
    registration:
      legacy:
        first_name: "input[name='firstName'], input[id*='firstName'], input[placeholder*='first']"
        last_name: "input[name='lastName'], input[id*='lastName'], input[placeholder*='last']"
        email: "input[name='email'], input[id*='email'], input[type='email']"
        phone: "input[name='phone'], input[id*='phone'], input[placeholder*='phone']"
        submit: "input[type='submit'], button[type='submit'], input[value*='register']"
      modern:
        first_name: "input[formControlName='firstName'], input[data-testid='firstName'], input[placeholder*='first']"
        last_name: "input[formControlName='lastName'], input[data-testid='lastName'], input[placeholder*='last']"
        email: "input[formControlName='email'], input[data-testid='email'], input[type='email']"
        phone: "input[formControlName='phone'], input[data-testid='phone'], input[placeholder*='phone']"
        submit: "button[type='submit'], button:contains('Register'), button:contains('Sign Up')"
    
    # Search form
    search:
      legacy:
        search_input: "input[name='search'], input[id*='search'], input[placeholder*='search']"
        search_button: "input[type='submit'], button[type='submit'], input[value*='search'], button:contains('Search')"
      modern:
        search_input: "input[formControlName='search'], input[data-testid='search'], input[placeholder*='search'], input[aria-label*='search']"
        search_button: "button[type='submit'], button:contains('Search'), button[aria-label*='search']"
    
    # Contact form
    contact:
      legacy:
        name: "input[name='name'], input[id*='name'], input[placeholder*='name']"
        email: "input[name='email'], input[id*='email'], input[type='email']"
        message: "textarea[name='message'], textarea[id*='message'], textarea[placeholder*='message']"
        submit: "input[type='submit'], button[type='submit'], input[value*='send'], input[value*='submit']"
      modern:
        name: "input[formControlName='name'], input[data-testid='name'], input[placeholder*='name']"
        email: "input[formControlName='email'], input[data-testid='email'], input[type='email']"
        message: "textarea[formControlName='message'], textarea[data-testid='message'], textarea[placeholder*='message']"
        submit: "button[type='submit'], button:contains('Send'), button:contains('Submit')"

  # Navigation mappings
  navigation:
    legacy:
      main_menu: "nav, .menu, .navigation, ul[id*='menu'], ul[class*='menu']"
      home_link: "a[href*='home'], a[href='/'], a:contains('Home'), a[title*='home']"
      about_link: "a[href*='about'], a:contains('About'), a[title*='about']"
      contact_link: "a[href*='contact'], a:contains('Contact'), a[title*='contact']"
      login_link: "a[href*='login'], a:contains('Login'), a:contains('Sign In')"
    modern:
      main_menu: "nav, [role='navigation'], .navbar, .header-nav"
      home_link: "a[routerLink='/'], a[href='/'], a:contains('Home'), a[data-testid='home']"
      about_link: "a[routerLink='/about'], a[href*='about'], a:contains('About'), a[data-testid='about']"
      contact_link: "a[routerLink='/contact'], a[href*='contact'], a:contains('Contact'), a[data-testid='contact']"
      login_link: "a[routerLink='/login'], a[href*='login'], a:contains('Login'), a:contains('Sign In')"

  # Action button mappings
  actions:
    legacy:
      save_button: "input[type='submit'][value*='save'], input[type='button'][value*='save'], button:contains('Save')"
      delete_button: "input[type='submit'][value*='delete'], input[type='button'][value*='delete'], button:contains('Delete')"
      edit_button: "input[type='button'][value*='edit'], button:contains('Edit'), a:contains('Edit')"
      cancel_button: "input[type='button'][value*='cancel'], button:contains('Cancel'), a:contains('Cancel')"
      add_button: "input[type='button'][value*='add'], button:contains('Add'), button:contains('New')"
    modern:
      save_button: "button:contains('Save'), button[data-testid='save'], button[aria-label*='save']"
      delete_button: "button:contains('Delete'), button[data-testid='delete'], button[aria-label*='delete']"
      edit_button: "button:contains('Edit'), button[data-testid='edit'], button[aria-label*='edit']"
      cancel_button: "button:contains('Cancel'), button[data-testid='cancel'], button[aria-label*='cancel']"
      add_button: "button:contains('Add'), button:contains('New'), button[data-testid='add']"

  # Data display mappings
  data_display:
    legacy:
      table: "table, .table, div[class*='table']"
      list: "ul, ol, .list, div[class*='list']"
      grid: ".grid, div[class*='grid'], table"
      card: ".card, .item, div[class*='card'], div[class*='item']"
    modern:
      table: "table, [role='table'], .mat-table, .table"
      list: "ul, ol, [role='list'], .mat-list, .list"
      grid: ".grid, .mat-grid, [role='grid'], div[class*='grid']"
      card: ".card, .mat-card, [role='article'], div[class*='card']"

  # Status and feedback mappings
  status:
    legacy:
      success_message: ".success, .message, div[class*='success'], span[class*='success']"
      error_message: ".error, .alert, div[class*='error'], span[class*='error']"
      loading_indicator: ".loading, .spinner, img[src*='loading'], div[class*='loading']"
    modern:
      success_message: ".success, .mat-snack-bar, [role='alert'][aria-live='polite'], div[class*='success']"
      error_message: ".error, .mat-error, [role='alert'][aria-live='assertive'], div[class*='error']"
      loading_indicator: ".loading, .mat-progress-spinner, [role='progressbar'], div[class*='loading']"

# Semantic equivalence rules
semantic_rules:
  # Form field types that are functionally equivalent
  field_types:
    text_input: ["input[type='text']", "input:not([type])", "input[formControlName]", "input[data-testid]"]
    email_input: ["input[type='email']", "input[name*='email']", "i
    nput[id*='email']"]
    password_input: ["input[type='password']", "input[name*='password']", "input[id*='password']"]
    number_input: ["input[type='number']", "input[name*='number']", "input[id*='number']"]
    select_dropdown: ["select", "mat-select", "[role='combobox']", ".dropdown"]
    checkbox: ["input[type='checkbox']", "mat-checkbox", "[role='checkbox']"]
    radio_button: ["input[type='radio']", "mat-radio-button", "[role='radio']"]
    textarea: ["textarea", "mat-form-field textarea", "[contenteditable='true']"]
    file_upload: ["input[type='file']", "mat-file-upload", "[role='button'][aria-label*='upload']"]

  # Button types that are functionally equivalent
  button_types:
    primary_action: ["button[type='submit']", "input[type='submit']", "button.primary", "button[data-testid*='submit']"]
    secondary_action: ["button[type='button']", "input[type='button']", "button.secondary", "a.button"]
    destructive_action: ["button.danger", "button.delete", "button[data-testid*='delete']", "button[aria-label*='delete']"]

# Comparison tolerance settings
comparison_settings:
  # Allow these differences in field counts
  field_count_tolerance: 2
  
  # Allow these differences in text content (fuzzy matching)
  text_similarity_threshold: 0.8
  
  # Ignore these attributes when comparing elements
  ignore_attributes: ["class", "style", "id", "data-cy", "data-testid"]
  
  # Consider these elements as equivalent even if structure differs
  structural_equivalence:
    - ["div", "section", "article"]
    - ["span", "p", "div"]
    - ["ul", "ol", "div[role='list']"]
    - ["table", "div[role='table']", "div.grid"]

